### ISSUE TITLE
ERROR: Dependency 'mtx' for 'bareos-common' not found! Build blocked.

### ISSUE THREAD

**Issue by unixfox** [asdil12/aurbs#29]
I tried to build bareos by adding only the package `bareos-common` to the build list but I found that the build blocked because AurBS didn't find the package `mtx` required by `bareos-storage-tape`:
```
[2018-05-30 13:30:24]  WARNING: No build for AUR-PKG 'bareos-common' --> building
[2018-05-30 13:30:24]    ERROR: Dependency 'mtx' for 'bareos-common' not found! Build blocked.
```
I think it's because the package doesn't exist but is provided by another package: [`mtx-svn`](https://aur.archlinux.org/packages/mtx-svn/)

@asdil12 Do you have a fix for this error?

**Comment by asdil12** [comment]
I added mtx-svn to the PKG list and this removed the dependency error

**Comment by asdil12** [comment]
As long as you run the latest aurbs version

**Comment by unixfox** [comment]
I forgot to think about that! Thank you it's fixed.
